language: node_js
os:
  - linux
node_js:
  - node 
  - lts/*
sudo: required
addons:
  chrome: stable
before_install:
  - |-
    if [ $TRAVIS_PULL_REQUEST == false ] && [ $TRAVIS_BRANCH == "master" ];
     then
        echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc;
      else
        echo "//registry.npmjs.org/:_authToken=\${NPM_INSTALL_TOKEN}" > ~/.npmrc;
    fi
  - 'git config --global url."git@github.com:".insteadOf "https://github.com/"'
install:
  - npm i -g @labshare/lsc codecov
  - npm install
  - npm rebuild
script:
  - npm run build
  - npm run lint
notifications:
  email: false
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: release
      if: branch = master
      node_js: lts/*
      before_deploy:
        - pip install --user awscli
        - aws configure set aws_access_key_id $AWS_ACCESS_TOKEN
        - aws configure set aws_secret_access_key $AWS_SECRET_TOKEN
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run semantic-release
      after_deploy:
        - ./extract_version.sh
        - aws s3 cp package_version s3://ui-electron-app/
        - rm -f package_version
    - stage: upload rpm to release 
      if: branch = master
      before_deploy:
        - wget https://builds.aws.labshare.org/artifactory/labshare/hedwig-api/hedwig-api-1.8.0.rpm 
      deploy:
        provider: releases
        name: ${TRAVIS_TAG} 
        api_key: $GH_TOKEN 
        file: hedwig-api-1.8.0.rpm 
        skip_cleanup: true
        on:
          tags: true
