language: node_js
os:
  - linux
node_js:
  - node 
  - lts/*
sudo: required
addons:
  chrome: stable
before_install:
  - |-
    if [ $TRAVIS_PULL_REQUEST == false ] && [ $TRAVIS_BRANCH == "master" ];
     then
        echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc;
      else
        echo "//registry.npmjs.org/:_authToken=\${NPM_INSTALL_TOKEN}" > ~/.npmrc;
    fi
  - 'git config --global url."git@github.com:".insteadOf "https://github.com/"'
install:
  - npm i -g @labshare/lsc codecov
  - npm install
  - npm rebuild
script:
  - npm run build
  - npm run lint
notifications:
  email: false
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: release
      if: branch = master
      node_js: lts/*
      before_deploy:
        - pip install --user awscli
        - aws configure set aws_access_key_id $AWS_ACCESS_TOKEN
        - aws configure set aws_secret_access_key $AWS_SECRET_TOKEN
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run semantic-release
      after_deploy:
        - ./extract_version.sh
        - aws s3 cp package_version s3://ui-electron-app/
        - sleep 10
    - stage: electron deployment
      if: branch = master
      os: osx
      osx_image: xcode7.2
      language: node_js
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - lsc build electron --platform=mac --buildVersion="$(curl -sL https://ui-electron-app.s3.amazonaws.com/package_version)"
    - stage: electron deployment
      if: branch = master
      os: win
      language: node_js
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - lsc build electron --platform=win --buildVersion="$(curl -sL https://ui-electron-app.s3.amazonaws.com/package_version)"
