language: node_js
os:
  - linux
node_js:
  - lts/*
sudo: required
addons:
  chrome: stable
before_install:
  - |-
    if [ $TRAVIS_PULL_REQUEST == false ] && [ $TRAVIS_BRANCH == "master" ];
     then
        echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc;
      else
        echo "//registry.npmjs.org/:_authToken=\${NPM_INSTALL_TOKEN}" > ~/.npmrc;
    fi
  - 'git config --global url."git@github.com:".insteadOf "https://github.com/"'
install:
  - npm i -g @labshare/lsc codecov
  - npm install
  - npm rebuild
script:
  - npm run build
  - npm run lint
notifications:
  email: false
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: release
      if: branch = master
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run semantic-release
    - stage: electron deployment
      if: branch = master
      os: osx
      osx_image: xcode7.2
      language: node_js
      node_js: lts/*
      script: skip
      before_deploy:
        # retrieving latest package json from master for version number
        - git fetch 
        - git merge origin/master
      deploy:
        provider: script
        skip_cleanup: true
        script: lsc build electron --platform=mac
    - stage: electron deployment
      if: branch = master
      os: win
      language: node_js
      node_js: lts/*
      script: skip
      before_deploy:
        # retrieving latest package json from master for version number
        - git fetch 
        - git merge origin/master
      deploy:
        provider: script
        skip_cleanup: true
        script: lsc build electron --platform=windows